name:                 v04
version:              0.1.0.0
visibility:           public
id:                   v04-0.1.0.0-Bf5p6VzO1yx5xhYP2UwXkQ
key:                  v04-0.1.0.0-Bf5p6VzO1yx5xhYP2UwXkQ
abi:                  9c2058baa895a4f3c6933fbb7cd1fd95
exposed:              True
exposed-modules:      AssocList ErrJst ZipTree
hidden-modules:       Paths_v04
import-dirs:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\lib\\x86_64-windows-ghc-9.6.7\\v04-0.1.0.0-Bf5p6VzO1yx5xhYP2UwXkQ"

library-dirs:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\lib\\x86_64-windows-ghc-9.6.7\\v04-0.1.0.0-Bf5p6VzO1yx5xhYP2UwXkQ"
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\lib\\x86_64-windows-ghc-9.6.7\\v04-0.1.0.0-Bf5p6VzO1yx5xhYP2UwXkQ"
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\lib\\x86_64-windows-ghc-9.6.7"
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\share\\x86_64-windows-ghc-9.6.7\\v04-0.1.0.0"

hs-libraries:         HSv04-0.1.0.0-Bf5p6VzO1yx5xhYP2UwXkQ
include-dirs:
    C:\Users\dgtut\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              base-4.18.3.0
haddock-interfaces:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\doc\\v04-0.1.0.0\\v04.haddock"

haddock-html:
    "C:\\Users\\dgtut\\OneDrive - Simon Fraser University (1sfu)\\Desktop\\CMPT 383\\docker\\synced\\v04\\.stack-work\\install\\d8d87e04\\doc\\v04-0.1.0.0"
